version: "3.9"

services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.6.0
    container_name: elastic-agent
    hostname: ${HOST?}
    restart: unless-stopped
    user: root
    environment:
      - FLEET_ENROLL=1
      - FLEET_URL=${FLEET_URL?}
      - FLEET_ENROLLMENT_TOKEN=${FLEET_ENROLLMENT_TOKEN?}

      # Timezone info
      - TZ=America/Vancouver
    volumes:
      # Persist agent state
      - agentdata:/usr/share/elastic-agent/state

      # Timezone info
      - ./zoneinfo/America/Vancouver:/usr/share/zoneinfo/America/Vancouver:ro

      # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro

volumes:
  agentdata:
